import sqlite3
conn = sqlite3.connect('db.sqlite3')
cursor = conn.cursor()
cursor.execute("DELETE FROM django_migrations WHERE app='hotel' AND name='0001_initial';")
conn.commit()
print("Deleted hotel 0001_initial from migrations")
cursor.execute("SELECT app, name FROM django_migrations;")
migrations = cursor.fetchall()
print("Applied migrations:", migrations)
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables:", tables)
cursor.execute("DROP TABLE IF EXISTS hotel_room;")
cursor.execute("DROP TABLE IF EXISTS hotel_userprofile;")
cursor.execute("DROP TABLE IF EXISTS hotel_booking;")
conn.commit()
print("Dropped hotel tables")
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
print("Tables:", tables)
conn.close()
